import { addCollection } from '@iconify/vue';

/**
 * Setup the iconify offline
 *
 * Registers every trimmed collection generated by `scripts/prepare-offline-icons.mjs`, so icons render without
 * requesting `api.iconify.design` (unreliable on some networks). Using a glob keeps newly added collections in
 * sync automatically — previously a hardcoded import list silently missed icons and left them blank.
 */
const collections = import.meta.glob('../assets/iconify/*.json', { eager: true });

export function setupIconifyOffline() {
  Object.values(collections).forEach(collection => {
    if (!collection) return;
    const data = (collection as any).default ?? collection;
    addCollection(data as any);
  });
}
